<?
/************************************************************************
* Classe permettant de recuperer le pays d'origine d'un visiteur        *
* Et de choisir la langue correspondante                                *
*                                                       03/03/04  22:37 *
*************************************************************************/
class getpays
{
	var $pays,$langues;
	
	function getpays()
	{
		$this->pays=liste_pays();
		$this->langues=array(
				"unknow"=>	"fr",
				"fr"	=>	"fr",
				"en"	=>	"en",
				);	
	}
	
	function get_pays() {
		$host=gethostbyaddr(divers::getip());
		$code = substr(strrchr($host,'.'),1);
		if($this->pays[$code])
		{
			return $this->pays[$code];
		}else{
			return "unknow";
		}
	}
	
	function get_lang()
	{
		$pays=$this->get_pays();
		if($this->langues[$pays])
		{
			return $this->langues[$pays];
		}else{
			return $this->langues["unknow"];
		}	
	}
	
	function liste_pays();
	{
		return array(
			'ad' => 'Andorra',
			'ae' => 'United Arab Emirates',
			'af' => 'Afghanistan',
			'ag' => 'Antigua And Barbuda',
			'ai' => 'Anguilla',
			'al' => 'Albania',
			'am' => 'Armenia',
			'an' => 'Netherlands Antilles',
			'ao' => 'Angola',
			'aq' => 'Antarctica',
			'ar' => 'Argentina',
			'as' => 'American Samoa',
			'at' => 'Austria',
			'au' => 'Australia',
			'aw' => 'Aruba',
			'az' => 'Azerbaijan',
			'ba' => 'Bosnia And Herzegovina',
			'bb' => 'Barbados',
			'bd' => 'Bangladesh',
			'be' => 'Belgium',
			'bf' => 'Burkina Faso',
			'bg' => 'Bulgaria',
			'bh' => 'Bahrain',
			'bi' => 'Burundi',
			'bj' => 'Benin',
			'bm' => 'Bermuda',
			'bn' => 'Brunei Darussalam',
			'bo' => 'Bolivia',
			'br' => 'Brazil',
			'bs' => 'Bahamas',
			'bt' => 'Bhutan',
			'bv' => 'Bouvet Island',
			'bw' => 'Botswana',
			'by' => 'Belarus',
			'bz' => 'Belize',
			'ca' => 'Canada',
			'cc' => 'Cocos (keeling) Islands',
			'cd' => 'Congo',
			'cf' => 'Central African Republic',
			'cg' => 'Congo',
			'ch' => 'Switzerland',
			'ci' => 'Cote D\'ivoire',
			'ck' => 'Cook Islands',
			'cl' => 'Chile',
			'cm' => 'Cameroon',
			'cn' => 'China',
			'co' => 'Colombia',
			'cr' => 'Costa Rica',
			'cu' => 'Cuba',
			'cv' => 'Cape Verde',
			'cx' => 'Christmas Island',
			'cy' => 'Cyprus',
			'cz' => 'Czech Republic',
			'de' => 'Germany',
			'dj' => 'Djibouti',
			'dk' => 'Denmark',
			'dm' => 'Dominica',
			'do' => 'Dominican Republic',
			'dz' => 'Algeria',
			'ec' => 'Ecuador',
			'ee' => 'Estonia',
			'eg' => 'Egypt',
			'eh' => 'Western Sahara',
			'er' => 'Eritrea',
			'es' => 'Spain',
			'et' => 'Ethiopia',
			'fi' => 'Finland',
			'fj' => 'Fiji',
			'fk' => 'Falkland Islands (malvinas)',
			'fm' => 'Micronesia',
			'fo' => 'Faroe Islands',
			'fr' => 'France',
			'ga' => 'Gabon',
			'gb' => 'United Kingdom',
			'gd' => 'Grenada',
			'ge' => 'Georgia',
			'gf' => 'French Guiana',
			'gh' => 'Ghana',
			'gi' => 'Gibraltar',
			'gl' => 'Greenland',
			'gm' => 'Gambia',
			'gn' => 'Guinea',
			'gp' => 'Guadeloupe',
			'gq' => 'Equatorial Guinea',
			'gr' => 'Greece',
			'gs' => 'South Georgia And The South Sandwich Islands',
			'gt' => 'Guatemala',
			'gu' => 'Guam',
			'gw' => 'Guinea-bissau',
			'gy' => 'Guyana',
			'hk' => 'Hong Kong',
			'hm' => 'Heard Island And Mcdonald Islands',
			'hn' => 'Honduras',
			'hr' => 'Croatia',
			'ht' => 'Haiti',
			'hu' => 'Hungary',
			'id' => 'Indonesia',
			'ie' => 'Ireland',
			'il' => 'Israel',
			'in' => 'India',
			'io' => 'British Indian Ocean Territory',
			'iq' => 'Iraq',
			'ir' => 'Iran',
			'is' => 'Iceland',
			'it' => 'Italy',
			'jm' => 'Jamaica',
			'jo' => 'Jordan',
			'jp' => 'Japan',
			'ke' => 'Kenya',
			'kg' => 'Kyrgyzstan',
			'kh' => 'Cambodia',
			'ki' => 'Kiribati',
			'km' => 'Comoros',
			'kn' => 'Saint Kitts And Nevis',
			'kp' => 'Korea',
			'kr' => 'Korea',
			'kw' => 'Kuwait',
			'ky' => 'Cayman Islands',
			'kz' => 'Kazakstan',
			'la' => 'Lao People\'s Democratic Republic',
			'lb' => 'Lebanon',
			'lc' => 'Saint Lucia',
			'li' => 'Liechtenstein',
			'lk' => 'Sri Lanka',
			'lr' => 'Liberia',
			'ls' => 'Lesotho',
			'lt' => 'Lithuania',
			'lu' => 'Luxembourg',
			'lv' => 'Latvia',
			'ly' => 'Libyan Arab Jamahiriya',
			'ma' => 'Morocco',
			'mc' => 'Monaco',
			'md' => 'Moldova',
			'mg' => 'Madagascar',
			'mh' => 'Marshall Islands',
			'mk' => 'Macedonia',
			'ml' => 'Mali',
			'mm' => 'Myanmar',
			'mn' => 'Mongolia',
			'mo' => 'Macau',
			'mp' => 'Northern Mariana Islands',
			'mq' => 'Martinique',
			'mr' => 'Mauritania',
			'ms' => 'Montserrat',
			'mt' => 'Malta',
			'mu' => 'Mauritius',
			'mv' => 'Maldives',
			'mw' => 'Malawi',
			'mx' => 'Mexico',
			'my' => 'Malaysia',
			'mz' => 'Mozambique',
			'na' => 'Namibia',
			'nc' => 'New Caledonia',
			'ne' => 'Niger',
			'nf' => 'Norfolk Island',
			'ng' => 'Nigeria',
			'ni' => 'Nicaragua',
			'nl' => 'Netherlands',
			'no' => 'Norway',
			'np' => 'Nepal',
			'nr' => 'Nauru',
			'nu' => 'Niue',
			'nz' => 'New Zealand',
			'om' => 'Oman',
			'pa' => 'Panama',
			'pe' => 'Peru',
			'pf' => 'French Polynesia',
			'pg' => 'Papua New Guinea',
			'ph' => 'Philippines',
			'pk' => 'Pakistan',
			'pl' => 'Poland',
			'pm' => 'Saint Pierre And Miquelon',
			'pn' => 'Pitcairn',
			'pr' => 'Puerto Rico',
			'ps' => 'Palestinian Territory',
			'pt' => 'Portugal',
			'pw' => 'Palau',
			'py' => 'Paraguay',
			'qa' => 'Qatar',
			're' => 'Reunion',
			'ro' => 'Romania',
			'ru' => 'Russian Federation',
			'rw' => 'Rwanda',
			'sa' => 'Saudi Arabia',
			'sb' => 'Solomon Islands',
			'sc' => 'Seychelles',
			'sd' => 'Sudan',
			'se' => 'Sweden',
			'sg' => 'Singapore',
			'sh' => 'Saint Helena',
			'si' => 'Slovenia',
			'sj' => 'Svalbard And Jan Mayen',
			'sk' => 'Slovakia',
			'sl' => 'Sierra Leone',
			'sm' => 'San Marino',
			'sn' => 'Senegal',
			'so' => 'Somalia',
			'sr' => 'Suriname',
			'st' => 'Sao Tome And Principe',
			'sv' => 'El Salvador',
			'sy' => 'Syrian Arab Republic',
			'sz' => 'Swaziland',
			'tc' => 'Turks And Caicos Islands',
			'td' => 'Chad',
			'tf' => 'French Southern Territories',
			'tg' => 'Togo',
			'th' => 'Thailand',
			'tj' => 'Tajikistan',
			'tk' => 'Tokelau',
			'tm' => 'Turkmenistan',
			'tn' => 'Tunisia',
			'to' => 'Tonga',
			'tp' => 'East Timor',
			'tr' => 'Turkey',
			'tt' => 'Trinidad And Tobago',
			'tv' => 'Tuvalu',
			'tw' => 'Taiwan',
			'tz' => 'Tanzania',
			'ua' => 'Ukraine',
			'ug' => 'Uganda',
			'um' => 'United States Minor Outlying Islands',
			'us' => 'United States',
			'uy' => 'Uruguay',
			'uz' => 'Uzbekistan',
			'va' => 'Holy See (vatican City State)',
			'vc' => 'Saint Vincent And The Grenadines',
			've' => 'Venezuela',
			'vg' => 'Virgin Islands',
			'vi' => 'Virgin Islands',
			'vn' => 'Viet Nam',
			'vu' => 'Vanuatu',
			'wf' => 'Wallis And Futuna',
			'ws' => 'Samoa',
			'ye' => 'Yemen',
			'yt' => 'Mayotte',
			'yu' => 'Yugoslavia',
			'za' => 'South Africa',
			'zm' => 'Zambia',
			'zw' => 'Zimbabwe'
			);
	}
}
?>